main: com.thepepeyt.Klasa.Main
name: DenoriaKlasy
version: 1.0.0
api-version: 1.13

depend:
  - PlaceholderAPI
  - Vault



commands:
  ustawklase:
    description: xD
  ustawrase:
    description: xD
  dodajwl:
    description: xD

  usunzwl:
    description: xD
  whitelista:
    description: xD
  czolgaj:
    description: xD
  dajvip:
    description: xD
  vip:
    description: xD
  dajmodel:
    description: xD
  me:
    description: xD
